Timestamp_Format: "dd.MM.yyyy HH:mm:ss"
Location_Format: "{world} [{x}, {y}, {z}]"

Command_Aliases: [ plugintemplate, template, plt ]

Locale: en

Prefix: "&8[&c${project.name}&8]&7 "
Log_Lag_Over_Milis: 100
Debug: [ ]
Version: 1